apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    app: webserver
spec:
  containers:
  - name: webserver
    image: dan513/webserver
    volumeMounts:
    - name: app
      mountPath: /app
  initContainers:
  - name: prepare
    image: busybox:1.34.0
    command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
    volumeMounts:
    - name: app
      mountPath: /app
  volumes:
  - name: app
    emptyDir: {}